Add skip_package_upload variable, remove old/unused files

diff --git a/build b/build
--- a/build
+++ b/build
@@ -64,32 +64,33 @@ docker cp ${container_id}:/omnibus-flapjack/pkg .
 echo "Purging the container"
 docker rm ${container_id}
 
-# Check if awscli exists
-if ! hash aws 2>/dev/null; then
-  echo "Installing awscli"
-  sudo apt-get install -y awscli
-fi
-
-# Check if aptly exists
-if ! hash aptly 2>/dev/null; then
-  if [ -f /etc/debian_version ]; then
-    echo "Installing aptly"
-    echo 'deb http://repo.aptly.info/ squeeze main' | sudo tee  /etc/apt/sources.list.d/aptly.list
-    gpg --keyserver keys.gnupg.net --recv-keys 2A194991
-    gpg -a --export 2A194991 | sudo apt-key add -
-
-    sudo apt-get update
-    if ! sudo apt-get install -y aptly ; then
-      echo "Error installing aptly." ; exit $? ;
-    fi
-
+if [ -z "${skip_package_upload}" ]; then
+  # Check if awscli exists
+  if ! hash aws 2>/dev/null; then
+    echo "Installing awscli"
+    sudo apt-get install -y awscli
   fi
-fi
 
-if [ ! -e aptly.conf ] ; then
-  echo "Creating aptly.conf"
-  # Create aptly config file
-    cat << EOF > aptly.conf
+  # Check if aptly exists
+  if ! hash aptly 2>/dev/null; then
+    if [ -f /etc/debian_version ]; then
+      echo "Installing aptly"
+      echo 'deb http://repo.aptly.info/ squeeze main' | sudo tee  /etc/apt/sources.list.d/aptly.list
+      gpg --keyserver keys.gnupg.net --recv-keys 2A194991
+      gpg -a --export 2A194991 | sudo apt-key add -
+
+      sudo apt-get update
+      if ! sudo apt-get install -y aptly ; then
+        echo "Error installing aptly." ; exit $? ;
+      fi
+
+    fi
+  fi
+
+  if [ ! -e aptly.conf ] ; then
+    echo "Creating aptly.conf"
+    # Create aptly config file
+      cat << EOF > aptly.conf
 {
   "rootDir": "${PWD}/aptly",
   "downloadConcurrency": 4,
@@ -105,49 +106,50 @@ if [ ! -e aptly.conf ] ; then
   "S3PublishEndpoints": {}
 }
 EOF
-fi
-# End aptly installation
-
-echo "Putting packages into aptly repo, syncing with S3"
-mkdir -p aptly
-aws s3 sync s3://packages.flapjack.io/aptly aptly --delete --acl public-read --region us-east-1
-
-echo "Creating all components for the distro release if they don't exist"
-for component in "${VALID_COMPONENTS[@]}"; do
-  if ! aptly -config=aptly.conf repo show flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-${component} &>/dev/null ; then
-    aptly -config=aptly.conf repo create -distribution ${DISTRO_RELEASE} -architectures="i386,amd64" -component=${component} flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-${component}
   fi
-done
+  # End aptly installation
 
-echo "Adding pkg/flapjack_${FLAPJACK_PACKAGE_VERSION}*.deb to the flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-experimental repo"
-if ! aptly -config=aptly.conf repo add flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-experimental pkg/flapjack_${FLAPJACK_PACKAGE_VERSION}*.deb ; then
-  echo "Error adding deb to repostory" ; exit $?
+  echo "Putting packages into aptly repo, syncing with S3"
+  mkdir -p aptly
+  aws s3 sync s3://packages.flapjack.io/aptly aptly --delete --acl public-read --region us-east-1
+
+  echo "Creating all components for the distro release if they don't exist"
+  for component in "${VALID_COMPONENTS[@]}"; do
+    if ! aptly -config=aptly.conf repo show flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-${component} &>/dev/null ; then
+      aptly -config=aptly.conf repo create -distribution ${DISTRO_RELEASE} -architectures="i386,amd64" -component=${component} flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-${component}
+    fi
+  done
+
+  echo "Adding pkg/flapjack_${FLAPJACK_PACKAGE_VERSION}*.deb to the flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-experimental repo"
+  if ! aptly -config=aptly.conf repo add flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-experimental pkg/flapjack_${FLAPJACK_PACKAGE_VERSION}*.deb ; then
+    echo "Error adding deb to repostory" ; exit $?
+  fi
+
+  echo "Attempting the first publish for all components of the major version of the given distro release"
+  publish_cmd='aptly -config=aptly.conf publish repo -architectures="i386,amd64" -gpg-key="803709B6" -component=, '
+  for component in ${VALID_COMPONENTS[@]}; do publish_cmd+="flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-${component} "; done
+  publish_cmd+=" ${FLAPJACK_MAJOR_VERSION}"
+  if ! eval $publish_cmd &>/dev/null ; then
+    echo "Repository already published, attempting an update"
+    # Aptly checks the inode number to determine if packages are the same.  As we sync from S3, our inode numbers change, so identical packages are deemed different.
+    aptly -config=aptly.conf -gpg-key="803709B6" -force-overwrite=true publish update ${DISTRO_RELEASE} ${FLAPJACK_MAJOR_VERSION}
+  fi
+
+  echo "Creating directory index files for published packages"
+  cd aptly/public
+  if ! ../../create_directory_listings . ; then
+    echo "Directory indexes failed to create"
+  fi
+  cd -
+
+  echo "Syncing the aptly db up to S3"
+  aws s3 sync aptly s3://packages.flapjack.io/aptly --delete --acl public-read --region us-east-1
+
+  echo "Syncing the public packages repo up to S3"
+  aws s3 sync aptly/public s3://packages.flapjack.io/deb --delete --acl public-read --region us-east-1
+
+  echo "Copying candidate deb for main to s3"
+  aws s3 cp pkg/candidate_flapjack_${FLAPJACK_PACKAGE_VERSION}*.deb s3://packages.flapjack.io/candidates --acl public-read --region us-east-1
+
+  echo "Done"
 fi
-
-echo "Attempting the first publish for all components of the major version of the given distro release"
-publish_cmd='aptly -config=aptly.conf publish repo -architectures="i386,amd64" -gpg-key="803709B6" -component=, '
-for component in ${VALID_COMPONENTS[@]}; do publish_cmd+="flapjack-${FLAPJACK_MAJOR_VERSION}-${DISTRO_RELEASE}-${component} "; done
-publish_cmd+=" ${FLAPJACK_MAJOR_VERSION}"
-if ! eval $publish_cmd &>/dev/null ; then
-  echo "Repository already published, attempting an update"
-  # Aptly checks the inode number to determine if packages are the same.  As we sync from S3, our inode numbers change, so identical packages are deemed different.
-  aptly -config=aptly.conf -gpg-key="803709B6" -force-overwrite=true publish update ${DISTRO_RELEASE} ${FLAPJACK_MAJOR_VERSION}
-fi
-
-echo "Creating directory index files for published packages"
-cd aptly/public
-if ! ../../create_directory_listings . ; then
-  echo "Directory indexes failed to create"
-fi
-cd -
-
-echo "Syncing the aptly db up to S3"
-aws s3 sync aptly s3://packages.flapjack.io/aptly --delete --acl public-read --region us-east-1
-
-echo "Syncing the public packages repo up to S3"
-aws s3 sync aptly/public s3://packages.flapjack.io/deb --delete --acl public-read --region us-east-1
-
-echo "Copying candidate deb for main to s3"
-aws s3 cp pkg/candidate_flapjack_${FLAPJACK_PACKAGE_VERSION}*.deb s3://packages.flapjack.io/candidates --acl public-read --region us-east-1
-
-echo "Done"
