Wait for an hour to get the flapjack upload lock, run the recover script before trying to do things with aptly, to work around the DB corruption issues

diff --git a/build b/build
--- a/build
+++ b/build
@@ -75,13 +75,25 @@ docker rm ${container_id}
 
 if [ -z "${skip_package_upload}" ]; then
   # Attempt to get lock file from S3
-  if aws s3 cp s3://packages.flapjack.io/flapjack_upload.lock flapjack_upload.lock --acl public-read --region us-east-1 1>/dev/null ; then
-    echo "Could not get flapjack upload lock, someone else is updating the repository"
-    exit 4
-  else
+  i="0"
+  while [ $i -lt 360 ]
+  do
+    if ! aws s3 cp s3://packages.flapjack.io/flapjack_upload.lock flapjack_upload.lock --acl public-read --region us-east-1 1>/dev/null ; then
+      success='true'
+      break
+    fi
+    echo "Could not get flapjack upload lock, someone else is updating the repository: ${i}"
+    sleep 10
+    i=$[$i+1]
+  done
+
+  if [ ! -z "${success}" ] ; then
     echo "Starting package upload"
     touch flapjack_upload.lock
     aws s3 cp flapjack_upload.lock s3://packages.flapjack.io/flapjack_upload.lock --acl public-read --region us-east-1 1>/dev/null
+  else
+    echo "Error: timed out trying to get flapjack_upload.lock"
+    exit 4
   fi
 
   # Check if awscli exists
@@ -131,6 +143,10 @@ EOF
   echo "Putting packages into aptly repo, syncing with S3"
   mkdir -p aptly
   aws s3 sync s3://packages.flapjack.io/aptly aptly --delete --acl public-read --region us-east-1
+
+  echo "Checking aptly db for errors"
+  aptly -config aptly.conf db recover
+  aptly -config aptly.conf db cleanup
 
   echo "Creating all components for the distro release if they don't exist"
   for component in "${VALID_COMPONENTS[@]}"; do
